version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6370:6379"  # Avoiding your 6379-6399 range

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: docprocessor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9010:9000" 
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: